### ISSUE TITLE
Upgrade to the latest web-vitals.js attribution build

### ISSUE THREAD

**Issue by rviscomi** [GoogleChrome/web-vitals-extension#110]

**Comment by rviscomi** [comment]
We should maybe also consider something like [dependabot](https://github.blog/2020-06-01-keep-all-your-packages-up-to-date-with-dependabot/) to keep this repo up to date with upstream [`web-vitals`](https://github.com/GoogleChrome/web-vitals) changes.

**Comment by rviscomi** [comment]
It seems like the version of web-vitals.js used by the extension is also so old that it's causing pages to be ineligible for [bfcache](https://web.dev/bfcache/#never-use-the-unload-event) due to it attaching an unload listener. This was fixed in https://github.com/GoogleChrome/web-vitals/pull/68 so upgrading should fix it.

**Comment by tunetheweb** [comment]
The latest version (3.3.1 at the time of writing) includes a standard and attribution build. Do you mean to upgrade to 3.3.1 AND switch to attribution? Or just to do the upgrade for now and have the ability to switch to attribution if we need it (e.g. for #112) at a later point?

**Comment by tunetheweb** [comment]
> It seems like the version of web-vitals.js used by the extension is also so old that it's causing pages to be ineligible for [bfcache](https://web.dev/bfcache/#never-use-the-unload-event) due to it attaching an unload listener. This was fixed in [GoogleChrome/web-vitals#68](https://github.com/GoogleChrome/web-vitals/pull/68) so upgrading should fix it.

This is incorrect. It was on a beta version of 3.0.0 but that was well after the unload handler was removed. Also I tested the new version and it still fails bfcache. But it's not complaining about unload handlers but about this:

> Extensions with long-lived connection attempted to send messages to frames in back/forward cache

Opened #117 for this as it's a separate issue.

**Comment by rviscomi** [comment]
Thanks for the correction :)

> Do you mean to upgrade to 3.3.1 AND switch to attribution? Or just to do the upgrade for now and have the ability to switch to attribution if we need it (e.g. for #112) at a later point?

This issue should be both upgrading the dependency and starting to make use of the new attribution info.

**Comment by tunetheweb** [comment]
This was completed.
